### ISSUE TITLE
Seeking Guidance on Enhancing Emoji Suggestion Feature for Multi-Language Support in Productivity App Development

### ISSUE THREAD

**Issue by yccheok** [jacobmarks/emoji_search#1]
I am developing a productivity mobile app and am interested in incorporating a feature that auto-suggests emojis based on user input for todo items. 

I've come across your work on converting text to emoji through semantic search and am impressed by the methodology and results shared, especially as someone without prior experience in AI and deep learning.

While your emoji-search feature seems to support only English keywords, I am considering extending this to multiple languages to enhance user experience. 

Based on your workflow shared in https://towardsdatascience.com/how-to-build-a-semantic-search-engine-for-emojis-ef4c75e3f7be, would adapting the model with a multi-language CLIP, similar to what's described at https://github.com/FreddeFrallan/Multilingual-CLIP, be a viable approach? 

I'm seeking guidance on any potential challenges or adjustments needed to support multi-language functionality effectively.

Thank you in advance for your insights and guidance.

**Comment by jacobmarks** [comment]
Hey @yccheok , thanks for reaching out! This sounds like a really cool idea for your app.

Absolutely, a multimodal CLIP model should do a pretty decent job. Curious to see how well you find it works — please let me know!
